### ISSUE TITLE
Allow metadata for a directory

### ISSUE THREAD

**Issue by mtilokani** [thephpleague/flysystem-aws-s3-v3#112]
How to allow a metadata for a directory ?

Currently metadata are stored for a directory but not getting while retrieving it.

Please help.

**Comment by twistor** [comment]
Most adapters don't support metadata for directories.

What adapter are you using?

**Comment by judgej** [comment]
This is a core flysystem issue. Flysystem will call `has()` on a metadata path. The `has()` method is only supposed to test if a *file* exists, not a directory. So fetching the metadata for a directory results in a "file does not exist" error. This can be fixed in the `has()` method of the driver, but  that will then be inconsistent with the documentation and the way the built-in Flysystem drivers work.

**Comment by frankdejonge** [comment]
This is a design decision for Flysystem. It is not focused on directories (only when needed).
