### ISSUE TITLE
Minio incompatiblity

### ISSUE THREAD

**Issue by tillkruss** [thephpleague/flysystem-aws-s3-v3#139]
We're using Minio during development and S3 in production.

Minio doesn't support object ACL's so all `GetObjectAcl` calls fail with:

```
Error executing "GetObjectAcl" on...
```

Right now we're just patching the `getRawVisibility()` method locally:

```php
protected function getRawVisibility($path)
{
    return AdapterInterface::VISIBILITY_PUBLIC;
}
```

Could we make this configurable or somehow easy to skip? Here is a fork that solves it: https://github.com/coraxster/flysystem-aws-s3-v3-minio/commit/bac95d4c2bab263974b3547fd6b01c3cf00caf92

The only solution for us right now is to overwrite Laravel's S3 filesystem driver, which is quite an extensive hassle.

Related #128.

**Comment by hescolar** [comment]
We are having the same problem with Flysystem + Minio

Thanks!

**Comment by hescolar** [comment]
A simple workaround:

``
use League\Flysystem\AdapterInterface;
use League\Flysystem\AwsS3v3\AwsS3Adapter;

class MinioAdapter extends AwsS3Adapter
{
    protected function getRawVisibility($path)
    {
        // @see https://github.com/thephpleague/flysystem-aws-s3-v3/issues/139
        // @see https://github.com/minio/minio/issues/4507
        return AdapterInterface::VISIBILITY_PUBLIC;
    }
}
``

**Comment by frankdejonge** [comment]
Hi, thanks for reporting this. I hope other people are helped by seeing this issue and a workaround. But since we can't fix it I'm closing the issue.

**Comment by bradjones1** [comment]
I understand this is closed, however if anyone is looking for a simple commit that you can diff and add to this package as a composer-patches patch, see https://github.com/bradjones1/flysystem-aws-s3-v3/commit/a5a8c0e8a91f57ed529e64d7159fdfcdaa6aaca4

... It might be nice to include something like this in the package itself, however I get if the maintainer thinks Minio incompatibility is a bit of an edge case. This is a little difficult to answer, though, since according to the AWS documentation I've read, ACL's are here to stay, and interplay with bucket policies in a way that is hard to merge locally. So, YMMV.
