### ISSUE TITLE
Feature: Copy from sourceBucket to anotherBucket

### ISSUE THREAD

**Issue by christoph-kluge** [thephpleague/flysystem-aws-s3-v3#142]
I had to copy a specific file from one bucket to another bucket w/o fetching the resource into memory. According to https://docs.aws.amazon.com/AmazonS3/latest/dev/CopyingObjectUsingPHP.html you're able to use `copyObject` with sourceBucket and targetBuckets. 

I did a quick proof-of-concept and adopted the adapter. If this feature is requested by the team I would prepare a proper PR for it. Please let me know :) 

Here is my solution: `$adapter->copy('/some/path', 's3://targetBucket/targetPath');` and below is the draft code. 

```
    public function copy($path, $newpath)
    {
        // use default 
        $toBucket = $this->bucket;
        $toKey = $this->applyPathPrefix($newpath);

        // if newPath is another s3: repository, replace toPath and toKey
        if (substr($newpath, 0, 4) == 's3:/') {
            $newpath = str_replace('s3:/', 'https://', $newpath);
            $toBucket = parse_url($newpath, PHP_URL_HOST);
            $toKey = $this->applyPathPrefix(parse_url($newpath, PHP_URL_PATH));
        }

        $command = $this->s3Client->getCommand(
            'copyObject',
            [
                'Bucket' => $toBucket,
                'Key' => $toKey,
                'CopySource' => urlencode($this->bucket . '/' . $this->applyPathPrefix($path)),
                'ACL' => $this->getRawVisibility($path) === AdapterInterface::VISIBILITY_PUBLIC
                    ? 'public-read' : 'private',
            ] + $this->options
        );
        // magic ....
    }
```

**Comment by frankdejonge** [comment]
Since this is outside of the scope of Flysystem and very specific to AWS S3 I recommend you to create a plugin for this.

**Comment by christoph-kluge** [comment]
Thanks for the quick reply, really appreciate it! Just to my understanding: isn't this flysystem-adapter very specific and only for AWS S3? This confuses me a bit.

**Comment by frankdejonge** [comment]
That's correct. But there's a broader goal/vision behind it. Flysystem adapters should never be used directly. They always need to be wrapped in a `Filesystem` instance. The adapters purpose is to fulfil that interface with the behaviour Flysystem expects. The focus of the core library is to provide a portable storage implementation for. In order to achieve this _isolation_ and _encapsulation_ are very important principles, because that's needed to work cross filesystem. The feature you're suggesting (while very useful to your case) breaks this encapsulation. Most of the time moving files across buckets are not standard operations (one-offs) and they're not part of the standard operations Flysystem aims to support. Therefor plugins are the way to go. I hope this explains my point of view.

**Comment by christoph-kluge** [comment]
Don't worry. I'm using this adapter within an laravel application which uses Flysystem as a Filesystem abstraction. Anyway thank you for the detailed explanation. This makes totally sense to me. 👍 

I will create a proper plugin/separate repository out of it. So if someone else stumbles upon this use-case might directly reuse it :)

**Comment by frankdejonge** [comment]
@christoph-kluge 👍 if you've got the plugin up, feel free to send in a PR to include it with a link in the readme for others to find.
