### ISSUE TITLE
Is it really beta ? 

### ISSUE THREAD

**Issue by cloudson** [thephpleague/flysystem-aws-s3-v3#17]
I'm sorry for this question, but i see the first release major 1.0.0 but on README.md there is a [BETA] title. Do you guys approve the use in production?

**Comment by frankdejonge** [comment]
@cloudson at the time of the 1.0.0 release the aws sdk v3 wasn't released yet, it still isn't. I suggest you use league/flysystem-aws-s3-v2 for the time being. Especially since changes in the aws-sdk have resulted in broken builds for this adapter. Namespace changes have occured. I'll spend time fixing these issues when a stable version of v3 is released.

**Comment by cloudson** [comment]
Ok @frankdejonge , thank you very much for this answer.

**Comment by hannesvdvreken** [comment]
@cloudson AWS SDK v3 is out. https://github.com/aws/aws-sdk-php/releases/tag/3.0.0
