### ISSUE TITLE
stream_get_contents(): content truncated

### ISSUE THREAD

**Issue by jeffsrepoaccount** [thephpleague/flysystem-aws-s3-v3#37]
I am getting this error when attempting to transfer files that are larger than 2<sup>31</sup> - 1 bytes:

```
stream_get_contents(): content truncated from 2149894396 to 2147483647 bytes
```

Is this a hard upper limit, or is this related to an ini setting that I can change?  This is the line of code we are using that is doing the transfer:

```php
$to->write($destinationPath . $file, $from->read($filename));
```

Both `$to` and `$from` are instances of `Illuminate\Filesystem\FilesystemAdapter`, created by using the `Storage` facade:

```php
$s3 = Storage::disk('s3');
$local = Storage::disk('local');
```

Files lower than this limit transfer without issue, so I know my application configuration is set correctly for using S3 as a filesystem.

**Comment by frankdejonge** [comment]
@jeffsrepoaccount when dealing with significantly large files Laravel's decoration becomes the limiting factor (which will hopefully change in future releases). You'd be better off obtaining the Filesystem instance and using a readStream/writeStream combination, this will use streams instead of strings which is how it's handled like you're describing, it won't use the stream_get_contents function and more importantly so, it won't eat up all your application's memory. You can obtain the `League\Flysystem\Filesystem` instance like so: `Storage::disk('s3')->getDriver()` which is implemented here: [code](https://github.com/illuminate/filesystem/blob/5.1/FilesystemAdapter.php#L291).

**Comment by jeffsrepoaccount** [comment]
@frankdejonge thanks a bunch for the tip, really appreciate it!

**Comment by frankdejonge** [comment]
@jeffsrepoaccount no problem, if this fixes your issue, could you close the issue? If not, feel free to ask more questions.
